### ISSUE TITLE
Portable Lokole emails

### ISSUE THREAD

**Issue by nzola** [ascoderu/opwen-webapp#13]
It is convenient to have Lokole local users to be able to access their emails anywhere around the world where there is Internet. (ex Internet Cafe)
 
Sub-tasks for this issue:

- [x] In opwen-cloudserver, ensure that emails are stored in a queryable format (implemented by https://github.com/ascoderu/opwen-cloudserver/pull/241).
- [x] In opwen-webapp, dockerize the email app (implemented by https://github.com/ascoderu/opwen-webapp/pull/224).
- [x] In opwen-webapp, ensure user accounts get synced to cloud. (implemented by https://github.com/ascoderu/opwen-webapp/pull/227 and https://github.com/ascoderu/opwen-cloudserver/pull/249)
- [x] In opwen-webapp, add new SIM_TYPE for cloud-deployed email app which toggles:
  - [x] Azure-based implementation of [EmailStore](https://github.com/ascoderu/opwen-webapp/blob/65f7ad99008da12bd44a72646355172c3ad71fc8/opwen_email_client/domain/email/store.py#L9-L66) interface (this can leverage the Azure Storage abstractions in [storage.py](https://github.com/ascoderu/opwen-cloudserver/blob/3cfd59a407b5e6e207bcf37b873d0fe5af6982a7/opwen_email_server/services/storage.py) to interface with the [email storage (maps email id to email)](https://github.com/ascoderu/opwen-cloudserver/blob/3cfd59a407b5e6e207bcf37b873d0fe5af6982a7/opwen_email_server/integration/azure.py#L51) and the [mailbox storage (maps user email address to emails)](https://github.com/ascoderu/opwen-cloudserver/blob/3cfd59a407b5e6e207bcf37b873d0fe5af6982a7/opwen_email_server/integration/azure.py#L63)) (implemented by https://github.com/ascoderu/opwen-cloudserver/pull/287)
  - [x] Azure-based implementation of [UserStore](https://github.com/ascoderu/opwen-webapp/blob/c2bad50ec87d5e05e90b7a53f535049508e24ed9/opwen_email_client/domain/email/user_store.py#L11-L25) interface (implemented by https://github.com/ascoderu/opwen-cloudserver/pull/287)
  - [x] Azure-based implementation of [Sync](https://github.com/ascoderu/opwen-webapp/blob/75bc8d909077464d0a7c7e6c416d95bb97a18286/opwen_email_client/domain/email/sync.py#L29-L36) interface (implemented by https://github.com/ascoderu/opwen-cloudserver/pull/287)
- [x] In opwen-cloudserver, deploy email app container to cluster (implemented by https://github.com/ascoderu/opwen-cloudserver/pull/287)

**Comment by c-w** [comment]
I thought about this in the past. I'll be a fairly massive project, but technically doable. We already have a copy of all the emails in the cloud, so we just need to host a copy of the opwen-webap project on a public server and build an implementation of the [EmailStore](https://github.com/ascoderu/opwen-shared/blob/e3246a49056636522292444893d4f1b310c5a5bc/opwen_domain/email/interfaces.py#L6) interface that reads from the cloud email store.

@nzola: Is this a hard requirement for launching the Lokole project? If not: I'd say that we work on this after everything else is done and offer it as a follow-up feature.

**Comment by nzola** [comment]
I had this question come to me everywhere I demo or installed emails
system. Bu let's continue with what we have to do now to assess potential
users and partners. We can just tell our potential customers, if they ask,
Portable email is on the list of Lokole next features.

Thanks,
Nzola.

**Comment by c-w** [comment]
So for now you can answer that yes, it's possible, but we haven't built it yet.

**Comment by nzola** [comment]
Thanks!

**Comment by c-w** [comment]
Adding some background for @seylm who is interested in picking up this task.

There are two parts to the Lokole system: a client and a server. The client is the Flask application. This is what runs on the OrangePi devices in villages. The server runs in Azure and is responsible for receiving emails sent from the Lokoles and sending them into the world as well as delivering emails from the world to the Lokole.

![image](https://user-images.githubusercontent.com/1086421/32297660-333f1e82-bf26-11e7-8ffd-1d2dcfbc7c25.png)

The client Flask application is deployed onto an OrangePi, it stores all the emails applicable to that Lokole deployment in a SQLite database on the OrangePi (blue circle in diagram above). In the cloud, the server application stores all the emails in Azure in a combination of Blob storage for storing the email objects and Table storage for storing metadata and enabling searches (orange circle in diagram above).

The client Flask application accesses the SQLite email store through an interface: [EmailStore](https://github.com/ascoderu/opwen-webapp/blob/65f7ad99008da12bd44a72646355172c3ad71fc8/opwen_email_client/domain/email/store.py#L9-L66). As such, what we need to do in order to implement a web-accessible Lokole client Flask application is to implement the EmailStore interface in terms of the Azure-based storage. After that is done, we can deploy the client Flask application on a server and people will be able to access their emails via this web portal.

**Comment by c-w** [comment]
Sub-tasks for this issue:

- [ ] Create Azure-based implementation of [EmailStore](https://github.com/ascoderu/opwen-webapp/blob/65f7ad99008da12bd44a72646355172c3ad71fc8/opwen_email_client/domain/email/store.py#L9-L66) interface.
- [ ] Dockerize opwen-webapp Flask application.
- [ ] Deploy Docker container to Azure (e.g. via [Container Instances](https://azure.microsoft.com/en-us/services/container-instances/)).
- [ ] Add DNS entry for the new Lokole mail web portal.

**Comment by c-w** [comment]
@laura-barluzzi If you want to work on "Azure-based implementation of EmailStore interface", I would recommend this approach:

1) Copy [EmailStore](https://github.com/ascoderu/opwen-webapp/blob/65f7ad99008da12bd44a72646355172c3ad71fc8/opwen_email_client/domain/email/store.py#L9-L66) from the opwen-webapp repo into the opwen-cloudserver repo (we'll figure out proper code sharing later).

2) Make a subclass of EmailStore called AzureEmailStore which takes two arguments: an instance of [mailbox storage](https://github.com/ascoderu/opwen-cloudserver/blob/3cfd59a407b5e6e207bcf37b873d0fe5af6982a7/opwen_email_server/integration/azure.py#L63) and an instance of [email storage](https://github.com/ascoderu/opwen-cloudserver/blob/3cfd59a407b5e6e207bcf37b873d0fe5af6982a7/opwen_email_server/integration/azure.py#L51).

3) Implement the abstract methods in AzureEmailStore using the mailbox storage and the email storage. The mailbox storage is structured like this: `{user_email}/{sent,received}/{date}/{email_id} -> {email}`. The email storage is structured like this: `{email_id} -> {email}`. This means that for example if you want to implement the `EmailStore.get(self, email_id) -> dict` method, you would use the email storage to look up the email by its id and then return the dictionary. On the other hand if you want to implement the `EmailStore.inbox(self, email_address, page) -> Iterable[dict]` method, you'd use the mailbox storage to list the contents at a particular path (e.g. `{user_email}/received/*`) and then load the email dictionaries from there.

4) For testing, use unit tests for now. We'll figure out proper integration later.

**Comment by c-w** [comment]
Web access is now available: https://mailserver.lokole.ca/web/
