### ISSUE TITLE
Deleting emails option

### ISSUE THREAD

**Issue by nzola** [ascoderu/opwen-webapp#19]
I can't delete any emails at all.

**Comment by c-w** [comment]
I agree that delete would be useful to implement, especially given the limited space on the Lokole devices. Implementing this is not hard but a bit of work: we'll have to add a method to the email store to delete an email for a given id, add a route to delete an email for an id that calls to the delete method on the email store, add a button to the email view that calls to the route. We'll also have to make a change to the database to mark the relationships between emails and attachments as `ON DELETE CASCADE` so that we remove all attachments when an email gets deleted.

**Comment by c-w** [comment]
![image](https://user-images.githubusercontent.com/1086421/30248530-ccc6df66-9629-11e7-83d5-7d30c6adf573.png)
