### ISSUE TITLE
Unable to format text on mobile

### ISSUE THREAD

**Issue by c-w** [ascoderu/opwen-webapp#36]
On mobile devices, the keyboard's cut/copy/paste dialog overlaps our formatting controls (see screenshot below).

<img src="https://user-images.githubusercontent.com/1086421/34922910-ec77bf9a-f963-11e7-9ed6-fd50253dc67d.png" height="400" />

We should move the formatting controls to prevent this. The email creation page is rendered by [email_new.html](https://github.com/ascoderu/opwen-webapp/blob/687b4d971aa2f2484ddd62c1a35b35062a8c55aa/opwen_email_client/webapp/templates/email_new.html) and the WYSIWYG editor is initialized in [email_new.js](https://github.com/ascoderu/opwen-webapp/blob/687b4d971aa2f2484ddd62c1a35b35062a8c55aa/opwen_email_client/webapp/static/js/email_new.js).

**Comment by laura-barluzzi** [comment]
@c-w after a first look I have a couple of questions/comments:
1. This doesn't happen only on the phone. It happens also on the laptop if the touchscreen is enabled. So the issue is for touch-screen devices and for the first lines in the body text. See this screenshot:
![image](https://user-images.githubusercontent.com/16849118/43238234-5a21df74-905b-11e8-8f75-d8938f15af1e.png)

2. Couldn't we simply move the formatting options on the bottom instead of the top? (e.g. gmail) If not, what about simply ensuring a minimum space between the formatting options and the first line of text? (e.g. GitHub:). Only if we rule out these two options I will look into how to change the popup, which is triggered by a "touchend" event somehow.

**Comment by c-w** [comment]
Moving the formatting to the bottom sounds like a great fix, as does the minimum space. Feel free to implement what you believe is best.

**Comment by laura-barluzzi** [comment]
@c-w the library used (`wysihtml5` ) for populating the Message body section doesn't seem to provide any option to change the positioning of the toolbar. So unfortunately the ideal solution to move the toolbar under the `textarea` is not easily feasible.

Given the circumstances I will solve it with the other approach of adding padding/margin accordignly.
